/**
 * Write `src/stamp/render-digest.ts` from the rendering code in this checkout.
 *
 * `pnpm build` runs this before `tsc`, and `prepack` runs `pnpm build`. A
 * published `dist/` therefore carries the digest of the source it was compiled
 * from. The result is committed as well, because `build:check` and the test
 * suite both read the module before anything has been built.
 *
 * `--check` reports a stale committed file and writes nothing. CI runs that.
 *
 * The `.ts` extension on the import below is deliberate, for the reason
 * `gen-samples.ts` gives. Node runs this file through type stripping rather
 * than a compiler, and the specifier has to name the file that is there.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { renderDigest } from "../test/render-digest.ts";

const target = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
  "src",
  "stamp",
  "render-digest.ts",
);

/**
 * The whole of the generated module.
 *
 * The declaration is written already wrapped, because `pnpm lint` runs
 * `oxfmt --check` over `src/` and a sha256 always takes that line past the
 * 80 columns oxfmt allows.
 */
function moduleText(digest: string): string {
  return `// Generated by scripts/render-digest.ts. Do not edit.

/**
 * A digest of the rendering code this package ships. It covers the modules a
 * render reaches, the fonts bundled alongside them, and the installed versions
 * of the libraries that draw, encode, colour and measure.
 *
 * Every stamp carries it, and an upgrade re-renders only once it has moved.
 * \`test/render-digest.ts\` computes it, and \`docs/rebuilds/\` says what that
 * covers and what it misses.
 */
export const RENDER_DIGEST =
  ${JSON.stringify(digest)};
`;
}

const wanted = moduleText(renderDigest());
const current = existsSync(target) ? readFileSync(target, "utf8") : "";

if (current === wanted) {
  process.exit(0);
}

if (process.argv.includes("--check")) {
  console.error(
    `${path.relative(process.cwd(), target)} is out of date.` +
      " Run `pnpm render-digest` and commit the result.",
  );
  process.exit(1);
}

writeFileSync(target, wanted);
console.log(`wrote ${path.relative(process.cwd(), target)}`);
