// Generated by scripts/render-digest.ts. Do not edit.

/**
 * A digest of the rendering code this package ships. It covers the modules a
 * render reaches, the fonts bundled alongside them, and the installed versions
 * of the libraries that draw, encode, colour and measure.
 *
 * Every stamp carries it, and an upgrade re-renders only once it has moved.
 * `test/render-digest.ts` computes it, and `docs/rebuilds/` says what that
 * covers and what it misses.
 */
export const RENDER_DIGEST =
  "5feb1fe82f4d7613b4b1c6b245bc7bdc9311051ccbf8fb907ecb78b7539d9201";
